production:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: "ogury-redmine"
  secure: true
  private: true
  expires: 10000
  proxy: false

development:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: "ogury-redmine"
  secure: true
  private: true
  expires: 10000
  proxy: false
